name: Kontrol
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel requests beautifulsoup4
          
      - name: kbl.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python kbl.py
        
      - name: selcuk.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python selcuk.py    
        
      - name: DeÄŸiÅŸiklik KontrolÃ¼ ve Sahneleme
        id: degisiklik_kontrol
        run: |
          git add -A  # Yeni oluÅŸturulan klasÃ¶rleri (selcuk/kablo) git'e tanÄ±t
          # DeÄŸiÅŸiklik olup olmadÄ±ÄŸÄ±nÄ± kontrol et
          if [ -n "$(git status --porcelain)" ]; then
            echo "degisiklik=true" >> $GITHUB_OUTPUT
            echo "âœ… DeÄŸiÅŸiklik tespit edildi."
          else
            echo "degisiklik=false" >> $GITHUB_OUTPUT
            echo "â„¹ï¸ Herhangi bir deÄŸiÅŸiklik yok."
          fi
          
      - name: DeÄŸiÅŸiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "ğŸ”„ Kanallar gÃ¼ncellendi" \
                     -m "ğŸ“º Selcuk ve Kablo M3U8 dosyalarÄ± otomatik gÃ¼ncellendi" \
                     -m "ğŸ•’ Ä°ÅŸlem Tarihi: $(date)" \
                     -m "SHA: $GITHUB_SHA"
          git push
